apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: my-app-service
  type: LoadBalancer
